name = "dr-bhavin-admin"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_API_URL = "https://api.drbhavingarara.com/api"
NEXT_PUBLIC_SENTRY_DISABLED = "true"
